#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="${repo_root}/.ralph-tui/opencode/tmp"
fixtures_dir="${repo_root}/demo-fixtures"

mkdir -p "${tmp_dir}"
mkdir -p "${fixtures_dir}"

export TMPDIR="${tmp_dir}"
export TMP="${tmp_dir}"
export TEMP="${tmp_dir}"
export BUN_TMPDIR="${tmp_dir}"

cd "${repo_root}"

printf '%s\n' "seed: $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "${fixtures_dir}/seed.txt"
printf '%s\n' "shared: base line" > "${fixtures_dir}/shared.txt"

timestamp="$(date -u +%Y%m%d-%H%M%S)"
alpha_path="demo-fixtures/${timestamp}-task-alpha.txt"
shared_path="demo-fixtures/${timestamp}-task-shared.txt"
epic_title="E2E Demo Epic ${timestamp}"
epic_desc=$(cat <<'EOF'
Autogenerated demo epic for local E2E runs.
EOF
)

epic_id="$(bd create --type epic \
  --title "${epic_title}" \
  --description "${epic_desc}" \
  --labels "ralph,demo-e2e" \
  --priority 1 \
  --silent)"

task1_desc=$(cat <<EOF
Create a demo fixture file for E2E logging verification.

### Impact Table
| Path | Change | Purpose | Notes |
|------|--------|---------|------|
| ${alpha_path} | create | Simple file for smoke verification | |

**Acceptance Criteria:**
- [ ] ${alpha_path} exists with a short single-line message
- [ ] Changes are committed
EOF
)

task2_desc=$(cat <<EOF
Add a shared demo file that will be used by follow-up tasks.

### Impact Table
| Path | Change | Purpose | Notes |
|------|--------|---------|------|
| ${shared_path} | create | Shared file for follow-up tasks | |

**Acceptance Criteria:**
- [ ] ${shared_path} exists with one line: "shared: task-2"
- [ ] Changes are committed
EOF
)

task3_desc=$(cat <<EOF
Append to the shared demo file.

### Impact Table
| Path | Change | Purpose | Notes |
|------|--------|---------|------|
| ${shared_path} | modify | Append a line for sequencing check | |

**Acceptance Criteria:**
- [ ] ${shared_path} includes a second line: "shared: task-3"
- [ ] Changes are committed
EOF
)

task1_id="$(bd create --type task \
  --title "E2E-1: Create demo file" \
  --description "${task1_desc}" \
  --labels "ralph,demo-e2e" \
  --priority 1 \
  --parent "${epic_id}" \
  --silent)"

task2_id="$(bd create --type task \
  --title "E2E-2: Create shared file" \
  --description "${task2_desc}" \
  --labels "ralph,demo-e2e" \
  --priority 2 \
  --parent "${epic_id}" \
  --silent)"

task3_id="$(bd create --type task \
  --title "E2E-3: Append shared file" \
  --description "${task3_desc}" \
  --labels "ralph,demo-e2e" \
  --priority 3 \
  --parent "${epic_id}" \
  --silent)"

bd dep add "${task3_id}" "${task2_id}"

bd show "${epic_id}"
bd list --parent "${epic_id}"

agent_plugin="${RALPH_AGENT_PLUGIN:-opencode}"
agent_model="${RALPH_MODEL:-minimax/MiniMax-M2.1}"

bun run dev -- run \
  --tracker beads \
  --epic "${epic_id}" \
  --agent "${agent_plugin}" \
  --model "${agent_model}" \
  --force \
  --no-tui
